[versions]
kotlin = "1.9.21"
compose = "1.6.0"
coroutines = "1.7.3"
datetime = "0.5.0"
koin = "3.5.0"
koinCompose = "1.1.0"
mockk = "1.13.8"
junit = "5.10.1"
redmineApi = "3.1.3"
httpclient = "4.5.14"

[libraries]
redmine-api = { module = "com.taskadapter:redmine-java-api", version.ref = "redmineApi" }
httpclient = { module = "org.apache.httpcomponents:httpclient", version.ref = "httpclient" }
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "coroutines" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "datetime" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koinCompose" }
koin-test = { module = "io.insert-koin:koin-test", version.ref = "koin" }
koin-test-junit5 = { module = "io.insert-koin:koin-test-junit5", version.ref = "koin" }
mockk = { module = "io.mockk:mockk-jvm", version.ref = "mockk" }
junit = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
