package com.ps.redmine.resources

import com.ps.redmine.util.OSUtils

enum class Language {
    ENGLISH,
    FRENCH
}

object Strings {
    @Volatile
    private var currentLanguage = Language.FRENCH // Default initialization

    fun updateLanguage(language: String) {
        currentLanguage = when (language.lowercase()) {
            "en" -> Language.ENGLISH
            else -> Language.FRENCH  // Default to French for any other value or if not set
        }
    }


    private val strings = mapOf(
        Language.FRENCH to mapOf(
            "configuration_title" to "Configuration",
            "configuration_error" to "Veuillez remplir tous les champs",
            "redmine_uri" to "URL Redmine",
            "api_key" to "Clé d'API Redmine",
            "show_api_key" to "Afficher",
            "hide_api_key" to "Masquer",
            "save" to "Enregistrer",
            "settings" to "Paramètres",
            "impersonate_self" to "Moi-même",
            "impersonate_search_placeholder" to "Rechercher un utilisateur…",
            "impersonate_acting_as" to "Connecté en tant que",
            "impersonate_no_users" to "Aucun utilisateur",
            "language" to "Langue",
            "language_fr" to "Français",
            "language_en" to "Anglais",
            "error_dialog_title" to "Erreur",
            "error_dialog_message" to "Une erreur s'est produite lors de l'opération.",
            "error_api_unreachable" to "Impossible de se connecter à Redmine.\nVeuillez vérifier votre connexion internet et les paramètres de configuration (par exemple l'URL de Redmine et votre clé d'API).",
            "show_details" to "Afficher les détails techniques",
            "hide_details" to "Masquer les détails techniques",
            "hours_max_value" to "Les heures ne peuvent pas dépasser %.1f",
            "window_title" to "Suivi du temps Redmine",
            "project_label" to "Projet",
            "hours_label" to "Heures",
            "issue_label" to "Ticket",
            "activity_label" to "Activité",
            "comments_label" to "Commentaires",
            "comments_required" to "Les commentaires sont obligatoires",
            "select_issue_placeholder" to "Sélectionner un ticket",
            "add_entry" to "Ajouter (${OSUtils.formatShortcut("S", useModifier = true)})",
            "update_entry" to "Mettre à jour (${OSUtils.formatShortcut("S", useModifier = true)})",
            "cancel" to "Annuler (Esc)",
            "discard" to "Abandonner",
            "continue_editing" to "Continuer l'édition",
            "discard_changes_title" to "Abandonner les modifications ?",
            "discard_changes_message" to "Vous avez des modifications non sauvegardées. Êtes-vous sûr de vouloir les abandonner ?",
            "keyboard_shortcuts" to "Raccourcis clavier :\n${
                OSUtils.formatShortcut(
                    "S",
                    useModifier = true
                )
            } - Sauvegarder, Esc - Annuler",
            "today" to "Aujourd'hui",
            "today_shortcut" to "Aujourd'hui (Alt+T)",
            "set_to_today" to "Définir à aujourd'hui",
            "close" to "Fermer",
            "date_label" to "Date",
            "add_time_entry" to "Ajouter une saisie de temps",
            "edit_time_entry" to "Modifier la saisie de temps",
            "select_project_first" to "Sélectionnez d'abord un projet pour voir ses tickets",
            "new_entry" to "Nouvelle saisie",
            "previous" to "Précédent",
            "next" to "Suivant",
            "nav_previous" to "Précédent",
            "nav_next" to "Suivant",
            "nav_help" to "Alt+← Précédent | Alt+→ Suivant",
            "total_hours" to "Total des heures :",
            "error_loading_entries" to "Erreur lors du chargement des saisies de temps : %s",
            "entry_created" to "Saisie de temps créée avec succès",
            "entry_updated" to "Saisie de temps mise à jour avec succès",
            "operation_error" to "L'opération a peut-être réussi, mais il y a eu une erreur : %s",
            "cancel_shortcut" to "Annuler (Esc)",
            "set_to_today" to "Définir à aujourd'hui",
            "dropdown_up" to "▲",
            "dropdown_down" to "▼",
            "clear_button" to "✕",
            "clear_button_description" to "Effacer",
            "invalid_number" to "Veuillez saisir un nombre valide",
            "hours_must_be_positive" to "Les heures doivent être supérieures à 0",
            "no_projects" to "Aucun projet disponible",
            "no_activities" to "Aucune activité disponible",
            "showing_issue" to "Affichage actuel du ticket #%d",
            "hours_format" to "%.1f heures",
            "char_count" to "%d/255",
            "total_hours_format" to "%.1f",
            "issue_item_format" to "#%d %s",
            "issue_selection_format" to "#%d - %s",
            "time_entry_deleted" to "Saisie de temps supprimée avec succès",
            "dismiss" to "Fermer",
            "configuration_saved" to "Configuration enregistrée avec succès",
            "add_new_time_entry" to "Ajouter une nouvelle saisie de temps",
            "delete_time_entry" to "Supprimer la saisie de temps",
            "duplicate_time_entry" to "Dupliquer la saisie de temps",
            "duplicate_same_day" to "Pour ce jour",
            "duplicate_next_day" to "Pour le lendemain",
            "duplicate_range" to "Pour une plage…",
            "duplicate_range_title" to "Dupliquer sur une plage",
            "duplicate_range_from" to "Du",
            "duplicate_range_to" to "Au",
            "duplicate_range_confirm" to "Dupliquer",
            "duplicate_range_no_working_days" to "Aucun jour ouvré dans la plage sélectionnée",
            "duplicate_entries_created" to "%d saisies créées",
            "full_day" to "Journée complète",
            "loading_issues_for_project" to "Chargement des tickets ouverts pour le projet %s...",
            "loading_issues" to "Chargement des tickets...",
            "loading" to "Chargement...",
            "no_issues_for_project" to "Aucun ticket ouvert trouvé dans le projet %s",
            "no_issues_available" to "Aucun ticket disponible",
            "search" to "Rechercher",
            "no_items" to "Aucun élément disponible",
            "no_search_results" to "Aucun résultat trouvé",
            "missing_hours" to "Il manque %.1f heures pour atteindre %.1f heures",
            "excess_hours" to "Vous avez %.1f heures de plus que %.1f heures",
            "perfect_hours" to "Journée complète (%.1f heures) ✓",
            "dark_theme" to "Thème sombre",
            "previous_day" to "Jour précédent",
            "next_day" to "Jour suivant",
            "day_label" to "Jour",
            "version" to "Version",
            "api_key_help" to "Comment obtenir votre clé d'API Redmine ?",
            "api_key_help_content" to "Pour obtenir votre clé d'API Redmine :\n1. Connectez-vous à votre compte Redmine\n2. Accédez à 'Mon compte' (en haut à droite)\n3. Sur la page de votre compte, vous trouverez votre clé d'API dans la colonne de droite\n4. Si la clé n'est pas visible, cliquez sur 'Afficher' à côté de 'Clé d'accès API'\n5. Copiez cette clé et collez-la ici",
            "monthly_progress" to "Progression mensuelle :",
            "working_days" to "Jours ouvrables :",
            "expected_hours" to "Heures attendues :",
            "completion_percentage" to "%.1f%% complété",
            "month_completed" to "Mois complété ✓",
            "hours_remaining" to "%.1f heures restantes",
            "week_label" to "Sem. %d",
            "week_tooltip_dates" to "Sem. %d (%s – %s)",
            "week_tooltip_hours" to "%.1fh / %.1fh",
            "week_tooltip_current" to "Semaine en cours",
            "week_tooltip_non_worked" to "Aucun jour ouvré dans cette semaine",
            "calendar_tooltip_today" to "Aujourd'hui",
            "calendar_tooltip_selected" to "Date sélectionnée",
            "update" to "Mise à jour",
            "update_available_title" to "Mise à jour disponible",
            "update_version_format" to "Version %s",
            "update_release_notes" to "Notes de version",
            "update_open_release_page" to "Ouvrir la page de téléchargement",
            "update_download_for_os" to "Télécharger pour cet OS",
            "update_remind_later" to "Rappeler plus tard",
            "update_skip" to "Ignorer",
            "update_no_download_available" to "Aucun téléchargement disponible pour votre plateforme",
            "weekly_hours_label" to "Heures de travail par semaine",
            "hours_per_day" to "Heures par jour",
            "non_working_day_label" to "Jour non travaillé",
            "non_working_days_label" to "Jours non travaillés",
            "working_weekly_hours" to "Heures de travail hebdomadaires: %.1f",
            "monday" to "Lundi",
            "tuesday" to "Mardi",
            "wednesday" to "Mercredi",
            "thursday" to "Jeudi",
            "friday" to "Vendredi",
            "weekly_hours_range_error" to "Les heures hebdomadaires doivent être entre 7,5 et 39",
            "error_loading_projects" to "Impossible de charger les projets",
            "error_loading_issues_activities" to "Impossible de charger les tickets/activités",
            "error_saving_config" to "Échec de l'enregistrement de la configuration",
            "update_check_failed" to "Échec de la vérification de mise à jour",
            "confirm_delete_title" to "Supprimer cette saisie ?",
            "confirm_delete_message" to "Cette action est définitive. La saisie sera retirée de Redmine.",
            "confirm_delete_yes" to "Supprimer",
            "confirm_delete_no" to "Annuler",
            "empty_entries_title" to "Aucune saisie de temps",
            "empty_entries_subtitle" to "Ajoutez votre première saisie depuis le panneau de droite.",
            "loading_entries" to "Chargement des saisies…",
            "month_completed_celebration_title" to "Bravo !",
            "month_completed_celebration_subtitle" to "Le mois est entièrement saisi.",
            "select_entry" to "Sélectionner cette saisie",
            "selection_count" to "%d sélectionnée(s)",
            "clear_selection" to "Tout désélectionner",
            "bulk_edit" to "Modifier",
            "bulk_delete" to "Supprimer",
            "bulk_delete_title" to "Supprimer les saisies sélectionnées ?",
            "bulk_delete_message" to "Supprimer %d saisies ? Cette action est définitive.",
            "bulk_edit_title" to "Modifier les saisies sélectionnées",
            "bulk_edit_modify_project" to "Modifier le projet",
            "bulk_edit_modify_activity" to "Modifier l'activité",
            "bulk_edit_modify_issue" to "Modifier la demande",
            "bulk_edit_modify_hours" to "Modifier les heures",
            "bulk_edit_modify_comments" to "Modifier le commentaire",
            "bulk_edit_apply" to "Appliquer",
            "bulk_edit_mixed_projects" to "Activez « Modifier le projet » ou sélectionnez des saisies du même projet pour modifier l'activité ou la demande.",
            "bulk_entries_deleted" to "%d saisies supprimées",
            "bulk_entries_updated" to "%d saisies modifiées",
            "bulk_no_field_selected" to "Activez au moins un champ à modifier.",
            "help" to "Aide",
            "help_title" to "Aide",
            "help_overview_title" to "Présentation",
            "help_overview_body" to "RedmineTime permet de saisir et de suivre votre temps de travail dans Redmine. Le panneau de gauche affiche les saisies du mois sélectionné ; le panneau de droite sert à créer ou modifier une saisie. Les barres de progression à gauche indiquent l'avancement par semaine et pour le mois entier.",
            "help_entries_title" to "Saisies de temps",
            "help_action_edit" to "Cliquez sur une saisie dans la liste pour l'ouvrir et la modifier dans le panneau de droite.",
            "help_action_new" to "Désélectionnez la saisie en cours (ou changez de jour) pour afficher le formulaire de création.",
            "help_action_duplicate" to "Dupliquez une saisie sur le même jour, le lendemain ou sur une plage de dates ouvrées.",
            "help_action_delete" to "Supprimez la saisie sélectionnée (une confirmation est demandée).",
            "help_bulk_title" to "Modification groupée",
            "help_bulk_select" to "Cochez plusieurs saisies pour faire apparaître la barre d'actions groupées en haut de la liste.",
            "help_bulk_edit_action" to "Modifiez en lot le projet, l'activité, la demande, les heures ou le commentaire.",
            "help_bulk_delete_action" to "Supprimez plusieurs saisies en une seule opération.",
            "help_navigation_title" to "Navigation",
            "help_navigation_body" to "Naviguez entre les mois avec les flèches en haut de la liste ou avec Alt+← / Alt+→. Le bouton « Aujourd'hui » vous ramène au mois courant. Cliquez sur une barre hebdomadaire pour vous positionner sur le premier jour de cette semaine.",
            "help_impersonation_title" to "Saisir pour un autre utilisateur (admin)",
            "help_impersonation_body" to "Si votre compte Redmine est administrateur, cliquez sur votre nom dans le bandeau supérieur pour ouvrir le sélecteur d'utilisateurs. Choisissez un collègue : toutes les saisies de temps seront alors créées, modifiées et supprimées pour cet utilisateur. Un badge sur l'avatar et un libellé « Connecté en tant que » rappellent que vous êtes en mode impersonation. Sélectionnez « Moi-même » pour revenir à votre compte. Ce mode n'est jamais persisté : il est réinitialisé à chaque changement de configuration ou redémarrage.",
            "help_shortcuts_title" to "Raccourcis clavier",
            "help_shortcut_save" to "Enregistrer la saisie en cours",
            "help_shortcut_cancel" to "Annuler / fermer le dialogue",
            "help_shortcut_prev_month" to "Mois précédent",
            "help_shortcut_next_month" to "Mois suivant",
            "help_shortcut_today" to "Revenir au mois courant",
            "help_settings_title" to "Paramètres",
            "help_settings_body" to "L'icône Paramètres ouvre la configuration : URL Redmine, clé d'API, langue, thème sombre, heures par jour et jours non travaillés. Si vous êtes administrateur Redmine, le bandeau supérieur permet aussi de saisir le temps pour un autre utilisateur (impersonation).",
            "help_update_title" to "Mise à jour",
            "help_update_body" to "Lorsqu'une nouvelle version stable est publiée, un bouton « Mise à jour » apparaît dans le bandeau supérieur, marqué d'une pastille rouge. Cliquez dessus pour voir les notes de version et télécharger l'installateur adapté à votre système.",
        ),
        Language.ENGLISH to mapOf(
            "configuration_title" to "Configuration",
            "configuration_error" to "Please fill all fields",
            "redmine_uri" to "Redmine URL",
            "api_key" to "Redmine API Key",
            "show_api_key" to "Show",
            "hide_api_key" to "Hide",
            "save" to "Save",
            "settings" to "Settings",
            "impersonate_self" to "Myself",
            "impersonate_search_placeholder" to "Search user…",
            "impersonate_acting_as" to "Acting as",
            "impersonate_no_users" to "No users",
            "language" to "Language",
            "language_fr" to "French",
            "language_en" to "English",
            "error_dialog_title" to "Error",
            "error_dialog_message" to "An error occurred during the operation.",
            "error_api_unreachable" to "Unable to connect to Redmine.\nPlease check your internet connection and configuration settings (such as the URL of Redmine and your API key).",
            "show_details" to "Show technical details",
            "hide_details" to "Hide technical details",
            "hours_max_value" to "Hours cannot exceed %.1f",
            "window_title" to "Redmine Time Tracking",
            "project_label" to "Project",
            "hours_label" to "Hours",
            "issue_label" to "Issue",
            "activity_label" to "Activity",
            "comments_label" to "Comments",
            "comments_required" to "Comments are required",
            "select_issue_placeholder" to "Select an issue",
            "add_entry" to "Add Entry (${OSUtils.formatShortcut("S", useModifier = true)})",
            "update_entry" to "Update Entry (${OSUtils.formatShortcut("S", useModifier = true)})",
            "cancel" to "Cancel (Esc)",
            "discard" to "Discard",
            "continue_editing" to "Continue Editing",
            "discard_changes_title" to "Discard Changes?",
            "discard_changes_message" to "You have unsaved changes. Are you sure you want to discard them?",
            "keyboard_shortcuts" to "Keyboard shortcuts:\n${
                OSUtils.formatShortcut(
                    "S",
                    useModifier = true
                )
            } - Save, Esc - Cancel",
            "today" to "Today",
            "today_shortcut" to "Today (Alt+T)",
            "set_to_today" to "Set to Today",
            "close" to "Close",
            "date_label" to "Date",
            "add_time_entry" to "Add Time Entry",
            "edit_time_entry" to "Edit Time Entry",
            "select_project_first" to "Select a project first to see its issues",
            "new_entry" to "New entry",
            "previous" to "Previous",
            "next" to "Next",
            "nav_previous" to "Previous",
            "nav_next" to "Next",
            "nav_help" to "Alt+← Previous | Alt+→ Next",
            "total_hours" to "Total Hours:",
            "error_loading_entries" to "Error loading time entries: %s",
            "entry_created" to "Time entry created successfully",
            "entry_updated" to "Time entry updated successfully",
            "operation_error" to "Operation might have succeeded, but there was an error: %s",
            "cancel_shortcut" to "Cancel (Esc)",
            "set_to_today" to "Set to Today",
            "dropdown_up" to "▲",
            "dropdown_down" to "▼",
            "clear_button" to "✕",
            "clear_button_description" to "Clear",
            "invalid_number" to "Please enter a valid number",
            "hours_must_be_positive" to "Hours must be greater than 0",
            "no_projects" to "No projects available",
            "no_activities" to "No activities available",
            "showing_issue" to "Currently showing issue #%d",
            "hours_format" to "%.1f hours",
            "char_count" to "%d/255",
            "total_hours_format" to "%.1f",
            "issue_item_format" to "#%d %s",
            "issue_selection_format" to "#%d - %s",
            "time_entry_deleted" to "Time entry deleted successfully",
            "dismiss" to "Dismiss",
            "configuration_saved" to "Configuration saved successfully",
            "add_new_time_entry" to "Add new time entry",
            "delete_time_entry" to "Delete time entry",
            "duplicate_time_entry" to "Duplicate time entry",
            "duplicate_same_day" to "Same day",
            "duplicate_next_day" to "Next day",
            "duplicate_range" to "Date range…",
            "duplicate_range_title" to "Duplicate over a date range",
            "duplicate_range_from" to "From",
            "duplicate_range_to" to "To",
            "duplicate_range_confirm" to "Duplicate",
            "duplicate_range_no_working_days" to "No working days in the selected range",
            "duplicate_entries_created" to "%d entries created",
            "full_day" to "Full Day",
            "loading_issues_for_project" to "Loading open issues for project %s...",
            "loading_issues" to "Loading issues...",
            "loading" to "Loading...",
            "no_issues_for_project" to "No open issues found in project %s",
            "no_issues_available" to "No issues available",
            "search" to "Search",
            "no_items" to "No items available",
            "no_search_results" to "No search results",
            "missing_hours" to "Missing %.1f hours to reach %.1f hours",
            "excess_hours" to "You have %.1f hours more than %.1f hours",
            "perfect_hours" to "Full day (%.1f hours) ✓",
            "dark_theme" to "Dark Theme",
            "previous_day" to "Previous Day",
            "next_day" to "Next Day",
            "day_label" to "Day",
            "version" to "Version",
            "api_key_help" to "How to get your Redmine API key?",
            "api_key_help_content" to "To get your Redmine API key:\n1. Log in to your Redmine account\n2. Go to 'My account' (top right corner)\n3. On your account page, you'll find your API key in the right column\n4. If the key is not visible, click 'Show' next to 'API access key'\n5. Copy this key and paste it here",
            "monthly_progress" to "Monthly Progress:",
            "working_days" to "Working Days:",
            "expected_hours" to "Expected Hours:",
            "completion_percentage" to "%.1f%% completed",
            "month_completed" to "Month Completed ✓",
            "hours_remaining" to "%.1f hours remaining",
            "week_label" to "Week %d",
            "week_tooltip_dates" to "Week %d (%s – %s)",
            "week_tooltip_hours" to "%.1fh / %.1fh",
            "week_tooltip_current" to "Current week",
            "week_tooltip_non_worked" to "No working day in this week",
            "calendar_tooltip_today" to "Today",
            "calendar_tooltip_selected" to "Selected date",
            "update" to "Update",
            "update_available_title" to "Update Available",
            "update_version_format" to "Version %s",
            "update_release_notes" to "Release Notes",
            "update_open_release_page" to "Open download page",
            "update_download_for_os" to "Download for this OS",
            "update_remind_later" to "Remind Later",
            "update_skip" to "Skip",
            "update_no_download_available" to "No download available for your platform",
            "weekly_hours_label" to "Working hours per week",
            "hours_per_day" to "Hours per day",
            "non_working_day_label" to "Non-working day",
            "non_working_days_label" to "Non-working days",
            "working_weekly_hours" to "Weekly working hours: %.1f",
            "monday" to "Monday",
            "tuesday" to "Tuesday",
            "wednesday" to "Wednesday",
            "thursday" to "Thursday",
            "friday" to "Friday",
            "weekly_hours_range_error" to "Weekly hours must be between 7.5 and 39",
            "error_loading_projects" to "Failed to load projects",
            "error_loading_issues_activities" to "Failed to load issues/activities",
            "error_saving_config" to "Failed to save configuration",
            "update_check_failed" to "Update check failed",
            "confirm_delete_title" to "Delete this entry?",
            "confirm_delete_message" to "This action is permanent. The entry will be removed from Redmine.",
            "confirm_delete_yes" to "Delete",
            "confirm_delete_no" to "Cancel",
            "empty_entries_title" to "No time entries",
            "empty_entries_subtitle" to "Add your first entry from the panel on the right.",
            "loading_entries" to "Loading entries…",
            "month_completed_celebration_title" to "Well done!",
            "month_completed_celebration_subtitle" to "The whole month is logged.",
            "select_entry" to "Select this entry",
            "selection_count" to "%d selected",
            "clear_selection" to "Clear selection",
            "bulk_edit" to "Edit",
            "bulk_delete" to "Delete",
            "bulk_delete_title" to "Delete selected entries?",
            "bulk_delete_message" to "Delete %d entries? This action is permanent.",
            "bulk_edit_title" to "Edit selected entries",
            "bulk_edit_modify_project" to "Modify project",
            "bulk_edit_modify_activity" to "Modify activity",
            "bulk_edit_modify_issue" to "Modify issue",
            "bulk_edit_modify_hours" to "Modify hours",
            "bulk_edit_modify_comments" to "Modify comment",
            "bulk_edit_apply" to "Apply",
            "bulk_edit_mixed_projects" to "Enable 'Modify project' or pick entries sharing the same project to change activity or issue.",
            "bulk_entries_deleted" to "%d entries deleted",
            "bulk_entries_updated" to "%d entries updated",
            "bulk_no_field_selected" to "Enable at least one field to modify.",
            "help" to "Help",
            "help_title" to "Help",
            "help_overview_title" to "Overview",
            "help_overview_body" to "RedmineTime lets you log and track your working time in Redmine. The left panel shows the entries for the selected month; the right panel is used to create or edit an entry. The progress bars on the far left show your weekly and monthly progress.",
            "help_entries_title" to "Time entries",
            "help_action_edit" to "Click an entry in the list to open and edit it in the right panel.",
            "help_action_new" to "Deselect the current entry (or change day) to show the create form.",
            "help_action_duplicate" to "Duplicate an entry to the same day, the next day, or over a date range.",
            "help_action_delete" to "Delete the selected entry (a confirmation is requested).",
            "help_bulk_title" to "Bulk edit",
            "help_bulk_select" to "Tick several entries to reveal the bulk-action bar above the list.",
            "help_bulk_edit_action" to "Bulk edit the project, activity, issue, hours, or comment.",
            "help_bulk_delete_action" to "Delete several entries in a single operation.",
            "help_navigation_title" to "Navigation",
            "help_navigation_body" to "Move between months with the arrows above the list or with Alt+← / Alt+→. The \"Today\" button jumps back to the current month. Click a weekly bar to jump to the first day of that week.",
            "help_impersonation_title" to "Logging time for another user (admin)",
            "help_impersonation_body" to "If your Redmine account is an administrator, click your name in the top bar to open the user picker. Pick a teammate: all time entries will then be created, edited, and deleted on their behalf. A badge on the avatar and an \"Acting as\" label remind you that impersonation is active. Pick \"Myself\" to return to your own account. This mode is never persisted — it resets on any configuration change or restart.",
            "help_shortcuts_title" to "Keyboard shortcuts",
            "help_shortcut_save" to "Save the current entry",
            "help_shortcut_cancel" to "Cancel / close dialog",
            "help_shortcut_prev_month" to "Previous month",
            "help_shortcut_next_month" to "Next month",
            "help_shortcut_today" to "Jump back to the current month",
            "help_settings_title" to "Settings",
            "help_settings_body" to "The Settings icon opens the configuration: Redmine URL, API key, language, dark theme, daily hours and non-working days. If you are a Redmine administrator, the top bar also lets you log time on behalf of another user (impersonation).",
            "help_update_title" to "Updates",
            "help_update_body" to "When a new stable release is published, an \"Update\" button appears in the top bar with a red dot. Click it to view release notes and download the installer for your platform.",
        )
    )

    operator fun get(key: String): String {
        val result = if (currentLanguage == Language.FRENCH) {
            // For French, try French first, then fall back to English
            strings[Language.FRENCH]?.get(key) ?: strings[Language.ENGLISH]?.get(key) ?: key
        } else {
            // For English, try English first, then fall back to French
            strings[Language.ENGLISH]?.get(key) ?: strings[Language.FRENCH]?.get(key) ?: key
        }
        return result
    }
}
