name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: wrapper
        cache-read-only: false
        cache-overwrite-existing: true

    - name: Build with Gradle
      run: ./gradlew build

    - name: Run tests
      run: ./gradlew test

    - name: Create distribution package
      run: ./gradlew createDistributable

    - name: Package application (Windows)
      if: matrix.os == 'windows-latest'
      shell: pwsh
      run: ./gradlew packageMsi

    - name: Package application (macOS)
      if: matrix.os == 'macos-latest'
      shell: bash
      run: ./gradlew packageDmg

    - name: Upload installers
      uses: actions/upload-artifact@v4
      with:
        name: installer-${{ matrix.os }}
        path: |
          build/compose/binaries/main/msi/*.msi
          build/compose/binaries/main/dmg/*.dmg
