name: Build and Test

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
    paths-ignore:
      - '**/*.md'
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: wrapper
          cache-read-only: false
          cache-overwrite-existing: true

      - name: Extract version from tag
        if: startsWith(github.ref, 'refs/tags/v')
        id: extract_version
        shell: bash
        run: |
          VERSION=$(echo ${GITHUB_REF#refs/tags/v})
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Update gradle.properties with tag version
        if: startsWith(github.ref, 'refs/tags/v')
        shell: bash
        run: |
          echo "Current VERSION environment variable: $VERSION"
          echo "Current VERSION from output: ${{ steps.extract_version.outputs.version }}"
          if [ -n "${{ steps.extract_version.outputs.version }}" ]; then
            VERSION="${{ steps.extract_version.outputs.version }}"
          fi
          echo "Using version: $VERSION"
          if [ "${{ matrix.os }}" == "macos-latest" ]; then
            sed -i '' 's/appVersion=.*/appVersion='"$VERSION"'/' gradle.properties
          else
            sed -i 's/appVersion=.*/appVersion='"$VERSION"'/' gradle.properties
          fi
          cat gradle.properties

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test

      - name: Package application (Windows MSI)
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: ./gradlew packageReleaseMsi

      - name: Package application (Windows Portable)
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          ./gradlew createReleaseDistributable
          Compress-Archive -Path build/compose/binaries/main-release/app/* -DestinationPath build/compose/binaries/main-release/RedmineTime-portable.zip

      - name: Package application (macOS)
        if: matrix.os == 'macos-latest'
        shell: bash
        run: ./gradlew packageReleaseDmg

      - name: Upload Windows MSI artifact
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: redmine-time-windows-installer
          path: build/compose/binaries/main-release/msi/*.msi

      - name: Upload Windows Portable artifact
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: redmine-time-windows-portable
          path: build/compose/binaries/main-release/RedmineTime-portable.zip

      - name: Upload macOS dmg
        if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v4
        with:
          name: redmine-time-macos
          path: build/compose/binaries/main-release/dmg/*.dmg

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download Windows MSI artifact
        uses: actions/download-artifact@v4
        with:
          name: redmine-time-windows-installer
          path: artifacts/windows-installer

      - name: Download Windows Portable artifact
        uses: actions/download-artifact@v4
        with:
          name: redmine-time-windows-portable
          path: artifacts/windows-portable

      - name: Download macOS artifact
        uses: actions/download-artifact@v4
        with:
          name: redmine-time-macos
          path: artifacts/macos

      - name: List downloaded artifacts
        run: find artifacts -type f | sort

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          name: RedmineTime ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: |
            artifacts/windows-installer/*.msi
            artifacts/windows-portable/*.zip
            artifacts/macos/*.dmg
